name: 'Slack PR Notifier'
description: 'Notifies Slack on PR events like opened, closed, or merged'

inputs:
  slack-webhook-url:
    description: 'The Slack webhook URL'
    required: true
  include-labels:
    description: 'Whether to include PR labels in the Slack message'
    required: false
    default: 'false'

runs:
  using: 'node16'
  main: 'index.js'
