name: 'Slack PR Notifier'
description: 'Notifies Slack on PR events like opened, closed, or merged'

inputs:
  slack-webhook-url:
    description: 'Slack webhook URL'
    required: true
  include-labels:
    description: 'Whether to include PR labels'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token to fetch PR file data'
    required: true

runs:
  using: 'node16'
  main: 'index.js'
