name: PR Slack Notifier

on:
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Slack PR Notifier
        uses: ./.github/actions/notify-slack
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          include-labels: 'true'
